### ISSUE TITLE
Any work on support for io.js?

### ISSUE THREAD

**Issue by gauravagarwalr** [wfarr/nodenv#19]
https://iojs.org/en/index.html

**Comment by CaseyLeask** [comment]
Hey @wfarr, happy to do the work for this, just let me know how you want it done.

**Comment by gauravagarwalr** [comment]
Hi.. Would love to help on this, its has all ready been ported on OiNutter's project of the same name.
https://github.com/OiNutter/nodenv/issues/10

**Comment by buritica** [comment]
:+1: how can we help?

**Comment by wfarr** [comment]
If someone wants to volunteer to take over maintenance of this project, happy to give them commit bit.

**Comment by cronopio** [comment]
@wfarr Hi man, maybe I can handle some of the open PRs like co-maintainer or something similar. Some of them make sense and could be added to make a new release.

Let me know if I can help with something else.

**Comment by wfarr** [comment]
> @wfarr Hi man, maybe I can handle some of the open PRs like co-maintainer or something similar. Some of them make sense and could be added to make a new release.

You have push access now. :metal:

**Comment by buritica** [comment]
:metal:

--
*Juan Pablo Buriticá*
t: @buritica

**Comment by cronopio** [comment]
:metal:

**Comment by cronopio** [comment]
To anyone interested on install io.js with nodenv can test the initial work on https://github.com/wfarr/nodenv/pull/21 that hopefully will land when release `v0.3.4` comes out.

**Comment by cronopio** [comment]
Hi, new release `v0.3.4` comes out with support to iojs.
Please test it and let me know if there any issue.
