### ISSUE TITLE
System Wide node libraries

### ISSUE THREAD

**Issue by rtgibbons** [wfarr/nodenv#9]
The scenario for this is on a shared server with many users. Right now we have a dev server, and each client or sometimes project, will have their own user account on the system. We use Grunt on all projects, and have a variety of projects in Node.js where we can't upgrade to the latest version. Nodenv solves this, but each user on the box would have to compile their versions of Node needed.

The goal here is to only have to do this once. The problem could become with install global node modules. 

What would be nice is to install node versions globally, and then nodenv would maintain `~/.nodenv` for each user, allowing node modules to be manipulated per user, and each user allowed to have their own version run separately.

**Comment by cronopio** [comment]
This issue was solved with the steps described on [Global install instructiones pull request.](https://github.com/wfarr/nodenv/pull/17)
